### ISSUE TITLE
Make AppVeyor CI run integration tests

### ISSUE THREAD

**Issue by olegsych** [olegsych/T4Toolbox#2]
The AppVeyor CI build only runs unit tests now because VS 2013 integration tests fail when setting up the experimental profile.

```
[00:00:00] Build started
[00:00:09] "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe" /RootSuffix Exp /ResetSettings General.vssettings /Embedding /Command File.Exit
[00:04:04] log4net:ERROR XmlHierarchyConfigurator: Could not create Appender [RollingFileAppender] of type [log4net.Appender.RollingFileAppender]. Reported error follows.
[00:04:04] System.IO.FileNotFoundException: Could not load file or assembly 'AWSToolkit.Util' or one of its dependencies. The system cannot find the file specified.
[00:04:04] File name: 'AWSToolkit.Util'
[00:04:04]    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throw
[00:04:04] OnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
[00:04:04]    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean
[00:04:04]  ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
[00:04:04]    at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& st
[00:04:04] ackMark)
[00:04:04]    at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
[00:04:04]    at log4net.Util.SystemInfo.GetTypeFromString(Assembly relativeAssembly, String typeName, Boolean throwOnError, Boolean ignoreCase)
[00:04:04]    at log4net.Util.System
[00:04:04] Info.GetTypeFromString(String typeName, Boolean throwOnError, Boolean ignoreCase)
[00:04:04]    at log4net.Util.TypeConverters.TypeConverter.ConvertFrom(Object source)
[00:04:04]    at log4net.Util.OptionConverter.ConvertStringTo(Type target, String txt)
[00:04:04]    at log4net.Reposi
[00:04:04] tory.Hierarchy.XmlHierarchyConfigurator.ConvertStringTo(Type type, String value)
[00:04:04]    at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
[00:04:04]    at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.Creat
[00:04:04] eObjectFromXml(XmlElement element, Type defaultTargetType, Type typeConstraint)
[00:04:04]    at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
[00:04:04]    at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.Create
[00:04:04] ObjectFromXml(XmlElement element, Type defaultTargetType, Type typeConstraint)
[00:04:04]    at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.SetParameter(XmlElement element, Object target)
[00:04:04]    at log4net.Repository.Hierarchy.XmlHierarchyConfigurator.ParseAp
[00:04:04] pender(XmlElement appenderElement)
```

**Comment by joymon** [comment]
I am getting this issue. Is there any workaround atleast not to run integration tests?
