### ISSUE TITLE
Release a version compatible with Visual Studio 2017

### ISSUE THREAD

**Issue by ScottRFrost** [olegsych/T4Toolbox#41]
Working with VS 2017 RC and I can't get T4 Toolbox working.

I tried renaming the vsix to .zip, unzipping, editing the manifest files, then putting it back together  but I get errors like the following:

Compiling transformation: The type 'TextTransformation' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.VisualStudio.TextTemplating.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Adding a ref to Microsoft.VisualStudio.TextTemplating.15.0 doesn't seem to help.

Edit : Adding nuget package Microsoft.VisualStudio.TextTemplating.14.0 doesn't seem to help.

**Comment by ybadragon** [comment]
This actually would be really useful. The only reason we haven't completely switched to VS 2017 yet is because we generate all of our services using the T4 toolbox and couldn't get it to work in 2017. Same issues you are having.

**Comment by amariniello** [comment]
Same pain here.. +1

**Comment by bortolin** [comment]
thomasonb I am in your same situation !

**Comment by Slokken** [comment]
+1

**Comment by zeOxx** [comment]
+1 here as well

**Comment by odelljl** [comment]
No. Good. Deed. Goes. Unpunished.  😂

Aloha from Tokyo .... Hope all is well Oleg.

Get Outlook for Android

**Comment by TobiVanHelsinki** [comment]
same problem here

**Comment by subgurim** [comment]
Exactly same problem here!!

**Comment by RobBlackmore** [comment]
+1

**Comment by jgveire** [comment]
+1

**Comment by RobinHerbots** [comment]
+1

**Comment by Intelli-Soft** [comment]
+1

**Comment by hagronnestad** [comment]
I have modified the extension to work in Visual Studio 2017. It works for me at least, give it a try and let me know. My only focus was getting the extension to work in VS2017, so it probably won't work in earlier versions.

A VSIX can be downloaded and installed from here:
https://github.com/hagronnestad/T4Toolbox/releases/tag/vs2017-b1

My fork:
https://github.com/hagronnestad/T4Toolbox

**Comment by Intelli-Soft** [comment]
Looks, that it works almost perfect! - THX a lot!

**Comment by nsgaga** [comment]
@hagronnestad thanks !
And I've had some issues building the code with 2017 (either original or the fork), opening the .sln just stalls the VS (Community edition + VS SDK checked on, if relevant).
1) I had to start the devenv /safemode - and then it opens ok,
2) and then you need to force NuGet (rebuild doesn't help, go to Manage NuGet for solution - and click 'Restore')  
...then just set "Release' and rebuild all. Some tests still fail but it generates the right .vsix file (\src\T4Toolbox.vsix\bin\Release\) and that's all you need.

**Comment by hagronnestad** [comment]
@nsgaga I had the same problem, I should have mentioned it. I had to activate "Lightweight solution load for all solutions" to get it to load. I did turn it off afterwards though and it continues to load for me now.

![image](https://cloud.githubusercontent.com/assets/1651402/23843882/05b27b0e-07bf-11e7-8e0f-322aa7e51579.png)

**Comment by zamap** [comment]
+1

**Comment by ooswald** [comment]
+1

**Comment by hagronnestad** [comment]
@zamap and @ooswald, did you try my build? I've been using it for a couple of weeks, seems to work fine. If anyone have time to create a pull request to merge it into the original project please do.
https://github.com/hagronnestad/T4Toolbox/releases/tag/vs2017-b1

**Comment by subgurim** [comment]
Hi @hagronnestad,

I'm working with your build for these last two weeks too, and it's working perfectly.

Thanks!!

**Comment by zamap** [comment]
@hagronnestad, tried to add custom command in context menu for project -> always run for all projects in solution

**Comment by jordanrobinson** [comment]
@hagronnestad Your extension works great! Only thing I thought I'd mention is that after the last VS update I had to uninstall and reinstall it to get it working again, but now it's working perfectly again.

**Comment by sclarke81** [comment]
@hagronnestad Have you thought about raising a pull request with your changes?

**Comment by floradu88** [comment]
@olegsych Can you please merge the work from @hagronnestad for vs2017?

**Comment by hagronnestad** [comment]
@sclarke81 Yes, I should probably do a pull request, I just wasn't sure if the changes I did would introduce any incompatibility issues or similar with older versions. Feel free to review my changes or fork my fork and make a PR.

**Comment by floradu88** [comment]
@hagronnestad the version I have installed from your repo LGTM.

**Comment by jwittner** [comment]
Must have! 👍

**Comment by aredfox** [comment]
+1 - please do a pull request
just installed & tested with new 15.2 as well @hagronnestad!

**Comment by cesarsouza** [comment]
Also tested with 15.3 Preview 1 and Preview 2 and working fine!

**Comment by sag3ll0** [comment]
+1

**Comment by olegsych** [comment]
I started a PR #47, incorporating changes from the @hagronnestad's fork. Unfortunately I can't get the `T4Toolbox.VisualStudio.IntegrationTests` to run. Can someone try installing the vsix from the latest [ci build](https://ci.appveyor.com/project/olegsych/t4toolbox/build/artifacts)?

**Comment by floradu88** [comment]
I got this error when I tried installing it:

08/08/2017 08:18:51 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__64_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream, String localeRelativeRoot, Boolean localize)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by olegsych** [comment]
Thanks @floradu88. I figured out what was wrong with the integration tests and published a new version to the [Visual Studio gallery](https://marketplace.visualstudio.com/items?itemName=OlegVSych.T4ToolboxforVisualStudio2017). Can you try installing it from the Visual Studio Extensions and Updates dialog?

**Comment by oguiulfo** [comment]
Getting this error (I have the VS 2015 version installed in VS2015 as well and it didn't require me to install another version of the .NET framework), what do you think?

Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'T4 Toolbox for Visual Studio 2017' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by ybadragon** [comment]
The error @oguiulfo is talking about is because the .net framework that is required is 4.7. We literally just fixed this at work today. It was found by extracting the vsix file and opening the extensions.manifest. We simply installed .Net Framework 4.7 and that error went away and it installed successfully.

**Comment by oguiulfo** [comment]
Ahh that explains it. I've been in crunch mode so long I didn't even notice 4.7 had come out. It says that 4.7 came default with Windows 10 Creator's update which explains why I don't have it - my dev machine is still on Windows 7!

**Comment by ybadragon** [comment]
We are also on Windows 7. Unfortunately when my co-worker was looking for this fix, he uninstalled a .Net Framework and basically corrupted his entire dev system. He was able to get it working again after about 6 hours of troubleshooting.

**Comment by olegsych** [comment]
Shoot. I thought that Visual Studio 2017 installed .NET 4.7. @thomasonb Which version of .NET do you have installed with VS 2017 on your Windows 7?

**Comment by floradu88** [comment]
@olegsych The new version from here https://marketplace.visualstudio.com/items?itemName=OlegVSych.T4ToolboxforVisualStudio2017 was successfully installed and works on my vs2017 pro on windows 10

**Comment by ybadragon** [comment]
@olegsych Sorry it took a while for me to see this, I had just left work. On Windows 10 Creators update I believe comes with .Net 4.7. On Windows 7, I believe it is 4.5.2. That is the latest version I had on my system prior to installing 4.7

**Comment by ybadragon** [comment]
On a related note, Visual Studio 15.3 just released, and that might install 4.7 as well.

**Comment by olegsych** [comment]
Thanks @floradu88, @thomasonb. For compatibility with older versions of Windows, I think it'll be best to revert T4Toolbox back to .NET 4.5.2.

**Comment by olegsych** [comment]
I ended up downgrading .NET to v4.6 instead of v4.5.2 because that's what Visual Studio 2017 itself appears to require. Specifically, `Microsoft.VisualStudio.Shell.15.0` has a dependency on an assembly built with .NET 4.6 and I couldn't build T4Toolbox with v4.5.2. 

Version [15.0.0.2](https://github.com/olegsych/T4Toolbox/releases/tag/v15.0.0.2) was [published](https://marketplace.visualstudio.com/items?itemName=OlegVSych.T4ToolboxforVisualStudio2017) a few minutes ago. Can someone running VS 2017 on Windows 7 without .NET 4.7 help verify it?
