### ISSUE TITLE
Could not load file or assembly 'T4Toolbox, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by Assam** [olegsych/T4Toolbox#5]
Hi,
After upgrading to latest version of T4Toolbox i am getting following exception:

```
Error   1   Errors were generated when initializing the transformation object. The transformation will not be run.  The following Exception was thrown:
System.IO.FileNotFoundException: Could not load file or assembly 'T4Toolbox, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'T4Toolbox, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null'

Server stack trace: 
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.ResolveObjectReference(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage.FixupForNewAppDomain()
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.IServiceProvider.GetService(Type serviceType)
   at T4Toolbox.TransformationContext.GetService(Type serviceType)
   at T4Toolbox.TransformationContext..ctor(TextTransformation transformation, StringBuilder generationEnvironment)
   at T4Toolbox.TransformationContext.Initialize(TextTransformation transformation, StringBuilder generationEnvironment)
   at Microsoft.VisualStudio.TextTemplatingBFAB6986108E94B1AC5A0E0C7B4E30903A3BB628F255F90A41F87609AC7BCC13849429B9F13396DC9DB3DC3A521BD2FFADF91307D99A8DB796F7F1B029FDB32F.GeneratedTextTransformation.Initialize() in c:\'mypath'\Model.tt:line 16
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()
=== Pre-bind state information ===
LOG: DisplayName = T4Toolbox, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
```

I appreciate any help to solve this issue.
Regards,
Assam Zafar

**Comment by olegsych** [comment]
Thanks for reporting this, @Assam. Would you mind collecting more information from your environment?
- Run the following PowerShell command to collect the codebase information the T4Toolbox package provides to Visual Studio. On my machine, I see entries that point to the T4Toolbox DLLs installed in my user extension cache.

```
get-childitem -path hkcu:\SOFTWARE\Microsoft\VisualStudio\12.0_Config\RuntimeConfiguration -recurse | where-object {$_.GetValue("name") -like "T4Toolbox*" }
```
- Run [fuslogvw](https://msdn.microsoft.com/en-us/library/e74a18c4.aspx), configure it to log all bindings to a custom folder and then repro the problem in Visual Studio. There will be a lot of bindings. You can find those relevant to T4Toolbox by running the following PowerShell command. In my environment, I see both failed and successful binding attempts for T4Toolbox assemblies that end up loading it from the extension installation directory. 

```
get-childitem -path C:\YourFolder -recurse | where-object {$_.name -like "*T4Toolbox*" }
```

**Comment by olegsych** [comment]
Build [12.10.1.38](https://github.com/olegsych/T4Toolbox/releases/tag/v12.10.1.38) has strongly-named assemblies. Can you try it in your environment?

CC: @Assam, @AGeekDad and @Maximushep.

**Comment by Maximushep** [comment]
The new version 12.10.1.38 works fine.

Thanks for your efforts in resolving this issue and your continuous efforts for this great tool.

**Comment by olegsych** [comment]
Thanks for confirming!
